-- Future anonymous product feedback
-- Run once in Supabase Dashboard -> SQL Editor.
-- Feedback is written only by the Cloudflare Worker with the service-role key.
-- No account id, email, task, journal, goal, habit name, or screenshot is stored.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  feedback_type text not null check (feedback_type in (
    'feature_broken',
    'cannot_find',
    'unclear_next_step',
    'cumbersome',
    'other'
  )),
  page_name text not null check (page_name in (
    'today',
    'week',
    'month',
    'year',
    'journal',
    'notes',
    'radio',
    'settings',
    'unknown'
  )),
  completion_status text not null check (completion_status in (
    'completed',
    'completed_with_effort',
    'not_completed'
  )),
  message_optional text check (
    message_optional is null or char_length(message_optional) <= 100
  ),
  anonymous_test_id uuid not null,
  app_version text not null check (char_length(app_version) between 1 and 40),
  device_type text not null check (device_type in (
    'mobile',
    'tablet',
    'desktop',
    'unknown'
  )),
  created_at timestamptz not null default now()
);

create table if not exists public.day7_survey (
  id bigint generated by default as identity primary key,
  usage_days text not null check (usage_days in ('0', '1', '2', '3-4', '5-7')),
  used_features text[] not null check (
    cardinality(used_features) >= 1
    and used_features <@ array[
      'today_todos',
      'pomodoro',
      'habits',
      'journal_reflection',
      'planning',
      'notes',
      'none'
    ]::text[]
    and not ('none' = any(used_features) and cardinality(used_features) > 1)
  ),
  reopen_intent text not null check (reopen_intent in ('yes', 'unsure', 'no')),
  primary_reason text not null check (
    (
      reopen_intent = 'yes'
      and primary_reason in ('plan_daily', 'see_growth', 'reduce_switching', 'atmosphere', 'other')
    )
    or (
      reopen_intent in ('unsure', 'no')
      and primary_reason in (
        'forget',
        'previous_tool',
        'operation_problem',
        'unclear_value',
        'no_need',
        'privacy',
        'other'
      )
    )
  ),
  desired_change_optional text check (
    desired_change_optional is null or char_length(desired_change_optional) <= 100
  ),
  anonymous_test_id uuid not null,
  created_at timestamptz not null default now()
);

create index if not exists feedback_created_at_idx
  on public.feedback (created_at desc);
create index if not exists feedback_type_page_idx
  on public.feedback (feedback_type, page_name, created_at desc);
create index if not exists feedback_completion_idx
  on public.feedback (completion_status, created_at desc);
create index if not exists feedback_anonymous_test_idx
  on public.feedback (anonymous_test_id, created_at desc);
create index if not exists day7_survey_created_at_idx
  on public.day7_survey (created_at desc);
create index if not exists day7_survey_intent_idx
  on public.day7_survey (reopen_intent, primary_reason, created_at desc);

alter table public.feedback enable row level security;
alter table public.day7_survey enable row level security;

-- There are intentionally no anon/authenticated RLS policies.
revoke all on table public.feedback from anon, authenticated;
revoke all on table public.day7_survey from anon, authenticated;
grant all on table public.feedback to service_role;
grant all on table public.day7_survey to service_role;
grant usage, select on sequence public.feedback_id_seq to service_role;
grant usage, select on sequence public.day7_survey_id_seq to service_role;

drop view if exists public.feedback_weekly_summary;
create view public.feedback_weekly_summary
with (security_invoker = true)
as
select
  feedback_type,
  page_name,
  completion_status,
  count(*)::bigint as report_count,
  count(distinct anonymous_test_id)::bigint as unique_testers
from public.feedback
where created_at >= now() - interval '7 days'
group by feedback_type, page_name, completion_status
order by report_count desc, feedback_type, page_name, completion_status;

create or replace view public.day7_survey_weekly_summary
with (security_invoker = true)
as
select
  reopen_intent,
  primary_reason,
  count(*)::bigint as response_count
from public.day7_survey
where created_at >= now() - interval '7 days'
group by reopen_intent, primary_reason
order by response_count desc, reopen_intent, primary_reason;

revoke all on table public.feedback_weekly_summary from anon, authenticated;
revoke all on table public.day7_survey_weekly_summary from anon, authenticated;
grant select on table public.feedback_weekly_summary to service_role;
grant select on table public.day7_survey_weekly_summary to service_role;
