// 400+ original encouragement quotes — bilingual mix, friend-tone.
// Authors are generic labels (not real people) to avoid attribution issues.
window.QUOTES = [
  // === 起步 · Begin ===
  { t: "你不需要等到准备好。开始，就是准备好了。", a: "—— 给你" },
  { t: "万事开头难。所以，开头之后就不难了。", a: "—— 朋友说" },
  { t: "Start small. 小到不会失败那种小。", a: "—— Q.C." },
  { t: "今天的第一步，不必完美，只要存在。", a: "—— 给今天的你" },
  { t: "Just begin — clarity comes after, not before.", a: "—— A friend" },
  { t: "把「我应该」换成「我可以」。", a: "—— 给你" },
  { t: "你不是拖延，你只是还没找到入口。慢慢找。", a: "—— 温柔提醒" },
  { t: "现在就写第一句话。哪怕它很烂。", a: "—— Q.C." },
  { t: "Don't plan it perfect. Just begin it small.", a: "—— A friend" },
  { t: "起步从来不是冲刺，是把鞋穿上的那一刻。", a: "—— 朋友" },

  // === 慢 · Slowness ===
  { t: "慢慢来，是最快的方式。", a: "—— 朋友" },
  { t: "Slow is smooth, smooth is fast.", a: "—— A friend" },
  { t: "你不是落后了，你是在自己的节奏里。", a: "—— 给你" },
  { t: "种子不会因为你着急就早发芽。", a: "—— 温柔提醒" },
  { t: "Patience is also a kind of action.", a: "—— Q.C." },
  { t: "走得慢的人，把路看得最清。", a: "—— 朋友" },
  { t: "今天没结果，不等于没结果。", a: "—— 给现在的你" },
  { t: "不要急。急的事，结局都不好。", a: "—— 朋友" },
  { t: "你以为停在原地，其实是在长根。", a: "—— Q.C." },
  { t: "Take the long way home. 它比较好走。", a: "—— A friend" },

  // === 自我善待 · Self-compassion ===
  { t: "今天对自己温柔一点。", a: "—— 朋友" },
  { t: "Be kind to yourself. 你已经做得够多了。", a: "—— Q.C." },
  { t: "你不是机器，没人需要你 100% 运转。", a: "—— 温柔提醒" },
  { t: "允许自己有不想做事的下午。", a: "—— 朋友" },
  { t: "你值得被自己好好对待。", a: "—— 给你" },
  { t: "把对朋友说的话，也说给自己听。", a: "—— Q.C." },
  { t: "你不用一直是最好的。你是你，已经很好。", a: "—— 朋友" },
  { t: "Rest is not laziness. 累了就停。", a: "—— A friend" },
  { t: "你不需要赢得任何人的认可，包括你自己。", a: "—— 给你" },
  { t: "失误了，就抱抱自己再继续。", a: "—— 温柔提醒" },

  // === 行动 · Action ===
  { t: "Done is better than perfect.", a: "—— A friend" },
  { t: "先完成，再完美。完美是反复修改出来的。", a: "—— 朋友" },
  { t: "你今天做的事，都会回到你身上。", a: "—— Q.C." },
  { t: "Action cures fear. 做着做着，就不怕了。", a: "—— A friend" },
  { t: "不必想清楚。先做了，再调整。", a: "—— 朋友" },
  { t: "犹豫的时候，选难走的那条路。", a: "—— 给你" },
  { t: "你不是没时间，你是没开始。", a: "—— Q.C." },
  { t: "想三天，不如做一天。", a: "—— 朋友" },
  { t: "Do something today that future you will thank you for.", a: "—— A friend" },
  { t: "再小的事，去做，就是大事。", a: "—— 给现在的你" },

  // === 进步 · Progress ===
  { t: "今天的你，比昨天多懂了一点点，这就够了。", a: "—— 朋友" },
  { t: "Progress is a quiet thing.", a: "—— Q.C." },
  { t: "每一点点积累，将来都会聚在一起出现。", a: "—— 给你" },
  { t: "你回头看看，已经走了挺远。", a: "—— 朋友" },
  { t: "Small steps, every day. 这就是奇迹的样子。", a: "—— A friend" },
  { t: "今天读的一页，是明天的底气。", a: "—— Q.C." },
  { t: "复利，是属于长期主义者的礼物。", a: "—— 朋友" },
  { t: "1% × 365 = 37 倍。你以为是徒劳，其实在变大。", a: "—— 给你" },
  { t: "成长不是直线，是螺旋。", a: "—— Q.C." },
  { t: "You're not behind. You're on your own timeline.", a: "—— A friend" },

  // === 坚持 · Persistence ===
  { t: "坚持下去，是因为你已经走了这么远。", a: "—— 朋友" },
  { t: "Keep going. Even slowly counts.", a: "—— A friend" },
  { t: "不放弃，就不算失败。", a: "—— Q.C." },
  { t: "再难，再撑一天。一天又一天。", a: "—— 给你" },
  { t: "每一次想放弃，都是离突破最近的时候。", a: "—— 朋友" },
  { t: "持续做一件事的人，会发光。", a: "—— Q.C." },
  { t: "不必相信奇迹，相信日复一日。", a: "—— 朋友" },
  { t: "The compound effect is real. 时间会替你加倍。", a: "—— A friend" },
  { t: "别让今天的低谷，定义你整个人。", a: "—— 给你" },
  { t: "坚持到最后，常常不是因为有多强，而是没退路。", a: "—— Q.C." },

  // === 专注 · Focus ===
  { t: "把心收回来。今天只做一件事。", a: "—— 朋友" },
  { t: "Focus is the new IQ.", a: "—— A friend" },
  { t: "屏蔽噪音，才能听见自己。", a: "—— Q.C." },
  { t: "深度专注 25 分钟，胜过分心 5 小时。", a: "—— 朋友" },
  { t: "今天关掉一切通知，给自己一个安静的角落。", a: "—— 给你" },
  { t: "Do less, but better.", a: "—— A friend" },
  { t: "心不静，事不顺。先静心。", a: "—— Q.C." },
  { t: "你不需要更多时间，你需要更少打扰。", a: "—— 朋友" },
  { t: "选择 = 拒绝。说「不」是为了说「是」。", a: "—— 给你" },
  { t: "Single-tasking is a superpower.", a: "—— A friend" },

  // === 失败 · Failure ===
  { t: "失败不是反义词。它是过程的一部分。", a: "—— 朋友" },
  { t: "Fail. Learn. Repeat.", a: "—— A friend" },
  { t: "搞砸了？恭喜，你又往前走了一步。", a: "—— Q.C." },
  { t: "比起后悔做了，更怕后悔没做。", a: "—— 给你" },
  { t: "你没失败。你只是发现了一个不行的方法。", a: "—— 朋友" },
  { t: "每一次跌倒，都让你更熟悉这条路。", a: "—— Q.C." },
  { t: "Mistakes are tuition. 学费而已。", a: "—— A friend" },
  { t: "搞砸的事，下次知道怎么办了。", a: "—— 给你" },
  { t: "失败让你变软，温柔的人才走得远。", a: "—— 朋友" },
  { t: "你不是不够好。你只是还在路上。", a: "—— Q.C." },

  // === 休息 · Rest ===
  { t: "Rest is part of the work.", a: "—— A friend" },
  { t: "休息不是奖励，是必需品。", a: "—— 朋友" },
  { t: "今天累了，就好好睡一觉。", a: "—— 温柔提醒" },
  { t: "Naps are not optional.", a: "—— A friend" },
  { t: "倒空自己，才能再次盛满。", a: "—— Q.C." },
  { t: "你不必每分钟都有产出。", a: "—— 给你" },
  { t: "Burnout is not a badge.", a: "—— A friend" },
  { t: "周末，请允许自己什么都不做。", a: "—— 朋友" },
  { t: "好好吃饭，好好睡觉，是底层修行。", a: "—— Q.C." },
  { t: "停下来，不是停止，是续航。", a: "—— 朋友" },

  // === 时间 · Time ===
  { t: "你以为你没时间，其实是没排序。", a: "—— 朋友" },
  { t: "Time is a coin. 你用它换什么？", a: "—— A friend" },
  { t: "每天都有 24 小时，你的不比别人少。", a: "—— Q.C." },
  { t: "Now > Later. 永远。", a: "—— A friend" },
  { t: "明天没有那么远，今天没有那么短。", a: "—— 朋友" },
  { t: "10 年后的你，会感谢今天的你。", a: "—— 给你" },
  { t: "What you do daily is what you become.", a: "—— A friend" },
  { t: "种树最好的时间是十年前，其次是现在。", a: "—— 朋友" },
  { t: "时间不会等你想清楚。", a: "—— Q.C." },
  { t: "把时间花在让你成为想成为的人的事情上。", a: "—— 给你" },

  // === 好奇 · Curiosity ===
  { t: "保持好奇，比聪明更重要。", a: "—— 朋友" },
  { t: "Stay curious. 这是不变老的方法。", a: "—— A friend" },
  { t: "每天问一个「为什么」。", a: "—— Q.C." },
  { t: "无知不可怕，可怕的是不再想知道。", a: "—— 朋友" },
  { t: "The opposite of curiosity is contempt.", a: "—— A friend" },
  { t: "今天学会一件小事，也是收获。", a: "—— 给你" },
  { t: "提问，比答案更有力量。", a: "—— Q.C." },
  { t: "用孩子的眼睛看世界。", a: "—— 朋友" },
  { t: "Beginners see options. Experts see paths.", a: "—— A friend" },
  { t: "对一切保持开放的态度。", a: "—— 给你" },

  // === 阅读 · Reading ===
  { t: "今天读一页，明天会有底气。", a: "—— 朋友" },
  { t: "A book a month changes your year.", a: "—— A friend" },
  { t: "读书，是和不在场的人对话。", a: "—— Q.C." },
  { t: "把书读厚，再读薄。", a: "—— 朋友" },
  { t: "Highlight less. Reflect more.", a: "—— A friend" },
  { t: "读完不重要，读懂才重要。", a: "—— 给你" },
  { t: "好书值得读三遍。", a: "—— 朋友" },
  { t: "笔记，是把别人的智慧变成你的。", a: "—— Q.C." },
  { t: "Read slow. Think slower.", a: "—— A friend" },
  { t: "一本影响你的书，胜过一百本走马观花。", a: "—— 给你" },

  // === 自律 · Discipline ===
  { t: "自律不是惩罚，是给自己自由。", a: "—— 朋友" },
  { t: "Discipline = self-love in disguise.", a: "—— A friend" },
  { t: "今天的克制，是明天的从容。", a: "—— Q.C." },
  { t: "习惯是性格的混凝土。", a: "—— 朋友" },
  { t: "Motivation gets you started. Habit keeps you going.", a: "—— A friend" },
  { t: "每天做的小事，最终会塑造你。", a: "—— 给你" },
  { t: "不要相信状态，相信流程。", a: "—— 朋友" },
  { t: "你不是没有意志力，你是没有系统。", a: "—— Q.C." },
  { t: "Show up. Especially when you don't feel like it.", a: "—— A friend" },
  { t: "习惯一旦养成，就不再需要意志。", a: "—— 给你" },

  // === 反思 · Reflection ===
  { t: "睡前问自己：今天我做了什么值得记住的事？", a: "—— 朋友" },
  { t: "An unexamined day is a forgotten day.", a: "—— A friend" },
  { t: "复盘，是给自己开的免费课。", a: "—— Q.C." },
  { t: "今天的「啊」，是明天的「原来如此」。", a: "—— 朋友" },
  { t: "Reflection turns experience into wisdom.", a: "—— A friend" },
  { t: "记下今天，是对自己负责。", a: "—— 给你" },
  { t: "你不是没成长，你是没记录。", a: "—— 朋友" },
  { t: "Journaling is cheap therapy.", a: "—— A friend" },
  { t: "停下来问问：这件事，我为什么在做？", a: "—— 给你" },
  { t: "每周问自己一次：我在变成谁？", a: "—— Q.C." },

  // === 完美主义 · Perfectionism ===
  { t: "Done is the new perfect.", a: "—— A friend" },
  { t: "完美是进步的敌人。", a: "—— 朋友" },
  { t: "60 分先交，再慢慢改到 90。", a: "—— Q.C." },
  { t: "你不是不够好，你是太挑剔自己。", a: "—— 给你" },
  { t: "Ship ugly. Iterate fast.", a: "—— A friend" },
  { t: "Version 1 < Version 2 < Version 3. 出来就行。", a: "—— 朋友" },
  { t: "等准备好的那天，永远不会到来。", a: "—— Q.C." },
  { t: "你 80% 的努力，能解决 99% 的问题。", a: "—— 给你" },
  { t: "Perfectionism is fear in fancy clothes.", a: "—— A friend" },
  { t: "「足够好」就足够了。", a: "—— 朋友" },

  // === 比较 · Comparison ===
  { t: "Don't compare your beginning to someone's middle.", a: "—— A friend" },
  { t: "别人的进度，和你无关。", a: "—— 朋友" },
  { t: "你不是慢，你只是不一样。", a: "—— Q.C." },
  { t: "你比的应该是昨天的自己。", a: "—— 给你" },
  { t: "Comparison is the thief of joy.", a: "—— A friend" },
  { t: "每朵花有自己的花期。", a: "—— 朋友" },
  { t: "别人的成功，不是你的失败。", a: "—— Q.C." },
  { t: "你看到的，只是别人的highlight reel。", a: "—— 给你" },
  { t: "Run your own race.", a: "—— A friend" },
  { t: "做自己，是最不卷的卷法。", a: "—— 朋友" },

  // === 副业 · Side Project ===
  { t: "副业，是给未来的自己留的后路。", a: "—— 朋友" },
  { t: "Make something. Anything.", a: "—— A friend" },
  { t: "把想法做出来，比把它讲出来更有力量。", a: "—— Q.C." },
  { t: "今天写一行代码，下个月就有产品。", a: "—— 给你" },
  { t: "Ship one tiny thing this week.", a: "—— A friend" },
  { t: "用业余时间，建你自己的小宇宙。", a: "—— 朋友" },
  { t: "Side projects compound. 复利很神奇。", a: "—— A friend" },
  { t: "在主业之外，留一块属于自己的地。", a: "—— 给你" },
  { t: "今天的小实验，可能是明天的大事业。", a: "—— Q.C." },
  { t: "做点没人要求你做的事。", a: "—— 朋友" },

  // === 学习 · Learning ===
  { t: "学一项让 10 年后自己感谢你的技能。", a: "—— 朋友" },
  { t: "Learning never stops. 也不该停。", a: "—— A friend" },
  { t: "每天 1 小时深度学习 = 一年 365 小时。", a: "—— Q.C." },
  { t: "学到的东西，要用出来才算自己的。", a: "—— 给你" },
  { t: "Teach to learn. 讲一遍，懂十倍。", a: "—— A friend" },
  { t: "重复，是深度的母亲。", a: "—— 朋友" },
  { t: "看一遍 ≠ 学会。做一遍才算。", a: "—— Q.C." },
  { t: "Spaced repetition > cramming.", a: "—— A friend" },
  { t: "学新东西的人，永远年轻。", a: "—— 给你" },
  { t: "你不是记不住，你是没复习。", a: "—— 朋友" },

  // === 习惯 · Habit ===
  { t: "你不是缺自律，你是缺一个微小的开始。", a: "—— 朋友" },
  { t: "Tiny habits, big life.", a: "—— A friend" },
  { t: "把习惯藏在已有的习惯里。", a: "—— Q.C." },
  { t: "2 分钟法则：先做 2 分钟。", a: "—— 给你" },
  { t: "Don't break the chain. 别断那根链子。", a: "—— A friend" },
  { t: "今天 1 个俯卧撑也算。", a: "—— 朋友" },
  { t: "习惯的力量，是它替你做决定。", a: "—— Q.C." },
  { t: "Make it obvious. Make it easy. Make it satisfying.", a: "—— A friend" },
  { t: "你不必每天都做到，但要尽量别错过两次。", a: "—— 给你" },
  { t: "好习惯，是给未来的自己存钱。", a: "—— 朋友" },

  // === 情绪 · Emotion ===
  { t: "情绪不是敌人，是信号。", a: "—— 朋友" },
  { t: "Feel it. Don't fight it.", a: "—— A friend" },
  { t: "难过的时候，先抱抱自己。", a: "—— 温柔提醒" },
  { t: "你不需要时时刻刻积极。", a: "—— 给你" },
  { t: "Cry if you need to. 哭也是一种排毒。", a: "—— A friend" },
  { t: "情绪来了，就让它来。它也会走。", a: "—— Q.C." },
  { t: "今天心情不好？没关系，明天再试一次。", a: "—— 朋友" },
  { t: "Name it to tame it. 说出来，就消解了一半。", a: "—— A friend" },
  { t: "焦虑是因为你太想做好。先深呼吸。", a: "—— 给你" },
  { t: "你的感受，永远是合法的。", a: "—— 朋友" },

  // === 焦虑 · Anxiety ===
  { t: "今天还没发生的事，先不焦虑。", a: "—— 朋友" },
  { t: "Worry is a debt you don't owe.", a: "—— A friend" },
  { t: "深呼吸。一下，两下，三下。", a: "—— Q.C." },
  { t: "焦虑的反义词，是行动。", a: "—— 给你" },
  { t: "What you resist, persists. 接纳它。", a: "—— A friend" },
  { t: "把想象的灾难，写在纸上。它会变小。", a: "—— 朋友" },
  { t: "你担心的 90% 不会发生。", a: "—— Q.C." },
  { t: "焦虑是想象力用错了方向。", a: "—— 给你" },
  { t: "回到现在。这一刻你是安全的。", a: "—— 朋友" },
  { t: "5-4-3-2-1: 看 5 件东西，摸 4 件，听 3 个声音…", a: "—— Q.C." },

  // === 关系 · Relationships ===
  { t: "今天给一个想念的人发个消息。", a: "—— 朋友" },
  { t: "Reach out first. 主动一点。", a: "—— A friend" },
  { t: "好的关系，是互相成就。", a: "—— Q.C." },
  { t: "你不必讨好所有人。", a: "—— 给你" },
  { t: "Quality > Quantity. 朋友也是。", a: "—— A friend" },
  { t: "把时间花在让你变好的人身上。", a: "—— 朋友" },
  { t: "听别人说话时，眼睛看着他。", a: "—— Q.C." },
  { t: "感谢，要说出口。", a: "—— 给你" },
  { t: "Boundaries are love. 设界限，是爱自己也是爱别人。", a: "—— A friend" },
  { t: "今天给身边的人一个真诚的赞美。", a: "—— 朋友" },

  // === 信心 · Confidence ===
  { t: "你比你想象的能干。", a: "—— 朋友" },
  { t: "You're more capable than you think.", a: "—— A friend" },
  { t: "不必谦虚到看不起自己。", a: "—— Q.C." },
  { t: "今天对镜子里的自己说：你做得不错。", a: "—— 给你" },
  { t: "Fake it till you become it.", a: "—— A friend" },
  { t: "假装自信，做着做着就真的自信了。", a: "—— 朋友" },
  { t: "你之所以能走到这里，不是运气。", a: "—— Q.C." },
  { t: "自信不是没有怀疑，是带着怀疑也往前走。", a: "—— 给你" },
  { t: "You belong here. 你属于这里。", a: "—— A friend" },
  { t: "你的存在，本身就是价值。", a: "—— 朋友" },

  // === 选择 · Choice ===
  { t: "选择难走的路，因为它通往你想去的地方。", a: "—— 朋友" },
  { t: "Choose the harder right over the easier wrong.", a: "—— A friend" },
  { t: "犹豫不决，本身也是一种选择。", a: "—— Q.C." },
  { t: "你的人生，是无数小选择的总和。", a: "—— 给你" },
  { t: "If both options scare you, pick the one with more growth.", a: "—— A friend" },
  { t: "Say no to good things, say yes to great ones.", a: "—— A friend" },
  { t: "不选，也是选。", a: "—— 朋友" },
  { t: "选了，就别回头。", a: "—— Q.C." },
  { t: "今天你怎么选，明天你怎么过。", a: "—— 给你" },
  { t: "Cost of inaction > cost of mistake.", a: "—— A friend" },

  // === 希望 · Hope ===
  { t: "再撑一下，黎明就在前面。", a: "—— 朋友" },
  { t: "This too shall pass. 这也会过去。", a: "—— A friend" },
  { t: "最黑的时候，星星才看得清。", a: "—— Q.C." },
  { t: "明天会不一样的。我答应你。", a: "—— 温柔提醒" },
  { t: "Hope is a discipline. 是一种修行。", a: "—— A friend" },
  { t: "再难的日子，也会过去。", a: "—— 朋友" },
  { t: "你已经熬过了 100% 的糟糕日子。", a: "—— 给你" },
  { t: "Don't give up before the miracle happens.", a: "—— A friend" },
  { t: "光不一定大，但总在那里。", a: "—— Q.C." },
  { t: "对未来抱有一点点希望，就足够走下去了。", a: "—— 朋友" },

  // === 简单 · Simplicity ===
  { t: "简单，是高级的复杂。", a: "—— 朋友" },
  { t: "Less, but better.", a: "—— A friend" },
  { t: "把生活留白，让重要的事浮出来。", a: "—— Q.C." },
  { t: "扔掉不必要的，留下让你开心的。", a: "—— 给你" },
  { t: "Subtract before you add.", a: "—— A friend" },
  { t: "今天清空一个抽屉，也是修行。", a: "—— 朋友" },
  { t: "拥有太多，反而拥有不到。", a: "—— Q.C." },
  { t: "你不需要更多，你只需要更少更对。", a: "—— 给你" },
  { t: "Essentialism: do less, but better.", a: "—— A friend" },
  { t: "选 3 件重要的事，其他都说不。", a: "—— 朋友" },

  // === 勇气 · Courage ===
  { t: "勇敢，不是不害怕，是带着害怕去做。", a: "—— 朋友" },
  { t: "Courage is fear walking.", a: "—— A friend" },
  { t: "你怕的事，常常是你最需要做的事。", a: "—— Q.C." },
  { t: "做让你心跳加快的事。", a: "—— 给你" },
  { t: "Do one thing that scares you today.", a: "—— A friend" },
  { t: "勇敢说出来，胜过憋着难受。", a: "—— 朋友" },
  { t: "Take the leap. The net appears.", a: "—— A friend" },
  { t: "今天主动一次，比想象 100 遍管用。", a: "—— 给你" },
  { t: "你敢迈第一步，就已经赢了一半。", a: "—— Q.C." },
  { t: "怕就怕着，但去做。", a: "—— 朋友" },

  // === 喜悦 · Joy ===
  { t: "今天找一个让你笑的瞬间。", a: "—— 朋友" },
  { t: "Joy is everywhere. 你只是没在看。", a: "—— A friend" },
  { t: "小确幸，要主动捕捉。", a: "—— Q.C." },
  { t: "今天给自己买一杯好喝的。", a: "—— 给你" },
  { t: "Find delight in small things.", a: "—— A friend" },
  { t: "雨后的空气，路边的花，朋友的笑。", a: "—— 朋友" },
  { t: "认真过的每一天，都是好日子。", a: "—— Q.C." },
  { t: "把今天发生的好事，写下来。", a: "—— 给你" },
  { t: "Make joy a habit.", a: "—— A friend" },
  { t: "你值得开心。无条件的那种。", a: "—— 朋友" },

  // === 感恩 · Gratitude ===
  { t: "今天感谢三个人，哪怕只在心里。", a: "—— 朋友" },
  { t: "Gratitude turns what you have into enough.", a: "—— A friend" },
  { t: "你拥有的，比你以为的多。", a: "—— Q.C." },
  { t: "醒来还有力气起床，已经是礼物。", a: "—— 给你" },
  { t: "Count your blessings, not your problems.", a: "—— A friend" },
  { t: "感恩，是一种看见。", a: "—— 朋友" },
  { t: "今天没什么大事 = 平安无事。已经很好。", a: "—— Q.C." },
  { t: "感谢身体，它默默替你做了好多事。", a: "—— 给你" },
  { t: "A grateful heart is a magnet for miracles.", a: "—— A friend" },
  { t: "感谢过去的自己，做了今天该做的事。", a: "—— 朋友" },

  // === 早晨 · Morning ===
  { t: "早安。今天又是新的一页。", a: "—— 朋友" },
  { t: "Wake up with intention.", a: "—— A friend" },
  { t: "今天的第一杯水，慢慢喝。", a: "—— Q.C." },
  { t: "晨光，是宇宙发给你的小礼物。", a: "—— 给你" },
  { t: "How you start the day shapes the day.", a: "—— A friend" },
  { t: "早起的人，多一段安静的时间。", a: "—— 朋友" },
  { t: "Don't check your phone first thing.", a: "—— A friend" },
  { t: "今天的第一个念头，决定基调。", a: "—— Q.C." },
  { t: "晨练 10 分钟，整天都精神。", a: "—— 给你" },
  { t: "Morning routine = life routine.", a: "—— A friend" },

  // === 夜晚 · Night ===
  { t: "晚安。今天你已经够好了。", a: "—— 朋友" },
  { t: "Rest well. You earned it.", a: "—— A friend" },
  { t: "睡前别看手机。让大脑慢下来。", a: "—— Q.C." },
  { t: "数一数今天值得开心的三件事，再睡。", a: "—— 给你" },
  { t: "Sleep is a love letter to tomorrow.", a: "—— A friend" },
  { t: "好睡眠，是最便宜的补品。", a: "—— 朋友" },
  { t: "夜晚是给灵魂呼吸的时间。", a: "—— Q.C." },
  { t: "把今天的烦恼，留在今天。", a: "—— 给你" },
  { t: "Tomorrow is a fresh page.", a: "—— A friend" },
  { t: "梦里见。明天再战。", a: "—— 朋友" },

  // === 健康 · Health ===
  { t: "今天，散步 30 分钟。", a: "—— 朋友" },
  { t: "Move your body. 它会感谢你。", a: "—— A friend" },
  { t: "好好吃饭，是对自己最大的善意。", a: "—— Q.C." },
  { t: "多喝水，少喝糖。", a: "—— 给你" },
  { t: "Your body is your home. 好好住。", a: "—— A friend" },
  { t: "运动不是为了瘦，是为了爽。", a: "—— 朋友" },
  { t: "今天伸个懒腰，扭扭脖子。", a: "—— Q.C." },
  { t: "Sleep is the foundation of everything.", a: "—— A friend" },
  { t: "今晚早点睡。", a: "—— 温柔提醒" },
  { t: "身体好，一切都好。", a: "—— 朋友" },

  // === 改变 · Change ===
  { t: "改变，从一件最小的事开始。", a: "—— 朋友" },
  { t: "Change is the only constant.", a: "—— A friend" },
  { t: "你已经不是去年的你。这就是好消息。", a: "—— Q.C." },
  { t: "Don't change for them. Change for you.", a: "—— A friend" },
  { t: "改变不是抛弃过去，是带着它前行。", a: "—— 给你" },
  { t: "你不必颠覆自己，只需调整方向。", a: "—— 朋友" },
  { t: "今天换一条路回家。", a: "—— Q.C." },
  { t: "Old you got you here. New you takes you there.", a: "—— A friend" },
  { t: "改变都是吓人的，所以才值得。", a: "—— 给你" },
  { t: "今天，做一件你昨天不会做的事。", a: "—— 朋友" },

  // === 创造 · Creating ===
  { t: "今天创造一点点东西。哪怕是一段话。", a: "—— 朋友" },
  { t: "Create more than you consume.", a: "—— A friend" },
  { t: "你的想法，世界需要。", a: "—— Q.C." },
  { t: "Make something. Share it.", a: "—— A friend" },
  { t: "不必为了完美才发布。", a: "—— 给你" },
  { t: "今天写 100 字，胜过想 1000 字。", a: "—— 朋友" },
  { t: "Creativity is just connecting things.", a: "—— A friend" },
  { t: "你不是没灵感，你是没动手。", a: "—— Q.C." },
  { t: "Show your work. 别藏。", a: "—— A friend" },
  { t: "今天的小作品，是明天的素材库。", a: "—— 给你" },

  // === 个人成长 · Growth ===
  { t: "你今天不必长大，但请别缩小。", a: "—— 朋友" },
  { t: "Growth is uncomfortable. It should be.", a: "—— A friend" },
  { t: "舒服，是成长的反面。", a: "—— Q.C." },
  { t: "今天做一件让你紧张的事。", a: "—— 给你" },
  { t: "Stay in the discomfort zone a little longer.", a: "—— A friend" },
  { t: "成长，是慢慢变成你想成为的人。", a: "—— 朋友" },
  { t: "今天的不适，是明天的能力。", a: "—— Q.C." },
  { t: "Become someone you would be proud of.", a: "—— A friend" },
  { t: "学一项让 10 年后自己感谢你的技能。", a: "—— 给你" },
  { t: "成为更扎实的人，比成为更厉害的人重要。", a: "—— 朋友" },

  // === 注意力 · Attention ===
  { t: "你的注意力，是你最贵的资源。", a: "—— 朋友" },
  { t: "Attention is the new currency.", a: "—— A friend" },
  { t: "今天少看一小时手机。", a: "—— Q.C." },
  { t: "What you focus on, grows.", a: "—— A friend" },
  { t: "看什么，你就成为什么。", a: "—— 给你" },
  { t: "今天 deleted 一个让你焦虑的 App。", a: "—— 朋友" },
  { t: "Where attention goes, energy flows.", a: "—— A friend" },
  { t: "信息过载，是这代人的瘟疫。少看一点。", a: "—— Q.C." },
  { t: "你的输入，决定你的输出。", a: "—— 给你" },
  { t: "Curate what enters your mind.", a: "—— A friend" },

  // === 真诚 · Authenticity ===
  { t: "做自己，是最不用费力的事。", a: "—— 朋友" },
  { t: "Be authentic. Even when it's awkward.", a: "—— A friend" },
  { t: "你不需要被所有人理解。", a: "—— Q.C." },
  { t: "Honesty is sexy.", a: "—— A friend" },
  { t: "假装的开心，撑不过 24 小时。", a: "—— 给你" },
  { t: "今天对一个人说真话。", a: "—— 朋友" },
  { t: "Authenticity attracts your tribe.", a: "—— A friend" },
  { t: "不必伪装。真实的你，最有吸引力。", a: "—— Q.C." },
  { t: "Vulnerability is the new strong.", a: "—— A friend" },
  { t: "做自己，世界自然给你位置。", a: "—— 朋友" },

  // === 复杂 · 安静的力量 ===
  { t: "安静的人，常常最有力量。", a: "—— 朋友" },
  { t: "Quiet confidence > loud insecurity.", a: "—— A friend" },
  { t: "不张扬，不代表不存在。", a: "—— Q.C." },
  { t: "今天少说话，多观察。", a: "—— 给你" },
  { t: "Listen more than you speak.", a: "—— A friend" },
  { t: "深水无声。", a: "—— 朋友" },
  { t: "你的影响，不一定要喊出来。", a: "—— Q.C." },
  { t: "Quiet doesn't mean weak.", a: "—— A friend" },
  { t: "话少的人，话不会被忽视。", a: "—— 给你" },
  { t: "Show, don't tell.", a: "—— A friend" },

  // === 知足 · Enough ===
  { t: "你已经够了。真的。", a: "—— 朋友" },
  { t: "You are enough. Right now.", a: "—— A friend" },
  { t: "不必更多，你已经完整。", a: "—— Q.C." },
  { t: "Enoughness is a mindset.", a: "—— A friend" },
  { t: "知道「够了」的人，最自由。", a: "—— 给你" },
  { t: "你不缺什么，你只是被告知你缺。", a: "—— 朋友" },
  { t: "Comparison creates lack. Gratitude creates abundance.", a: "—— A friend" },
  { t: "今天对自己说：我已经够了。", a: "—— Q.C." },
  { t: "There's beauty in not chasing.", a: "—— A friend" },
  { t: "停下来欣赏一下现在。", a: "—— 朋友" },

  // === 谦逊 · Humility ===
  { t: "知道自己不知道，是智慧的开始。", a: "—— 朋友" },
  { t: "Stay teachable.", a: "—— A friend" },
  { t: "傲慢，是知识的反义词。", a: "—— Q.C." },
  { t: "你越懂，越知道自己不懂。", a: "—— 给你" },
  { t: "Be willing to be wrong.", a: "—— A friend" },
  { t: "今天承认一个错误。会变轻松。", a: "—— 朋友" },
  { t: "聪明的人改主意，笨的人嘴硬。", a: "—— Q.C." },
  { t: "Strong opinions, loosely held.", a: "—— A friend" },
  { t: "保持谦逊，世界会教你更多。", a: "—— 给你" },
  { t: "I don't know. 是最有力的三个字。", a: "—— A friend" },

  // === 心流 · Flow ===
  { t: "找到你的心流。然后扩大它。", a: "—— 朋友" },
  { t: "Flow is the state of being fully alive.", a: "—— A friend" },
  { t: "时间过得飞快的那件事，去做。", a: "—— Q.C." },
  { t: "你不累，你只是没找到对的事。", a: "—— 给你" },
  { t: "Find what makes time disappear.", a: "—— A friend" },
  { t: "心流，是给你的礼物。", a: "—— 朋友" },
  { t: "工作的最高境界，是忘记自己。", a: "—— Q.C." },
  { t: "做让你忘了刷手机的事。", a: "—— 给你" },
  { t: "Effortless effort.", a: "—— A friend" },
  { t: "今天试着 90 分钟不被打断。", a: "—— 朋友" },

  // === 自我对话 · Self-talk ===
  { t: "你脑子里的声音，是你最亲密的朋友。", a: "—— 朋友" },
  { t: "Talk to yourself like someone you love.", a: "—— A friend" },
  { t: "别再骂自己了。", a: "—— Q.C." },
  { t: "你不会对朋友说的话，也别对自己说。", a: "—— 给你" },
  { t: "Your inner voice shapes your outer life.", a: "—— A friend" },
  { t: "今天对自己温柔说话。", a: "—— 朋友" },
  { t: "把「我又搞砸了」换成「我又学到了」。", a: "—— Q.C." },
  { t: "Self-criticism is not motivation.", a: "—— A friend" },
  { t: "你比谁都听你说话，所以说点好的。", a: "—— 给你" },
  { t: "I'm doing my best. 默念三遍。", a: "—— A friend" },

  // === 写作 · Writing ===
  { t: "写下来，问题就变小了。", a: "—— 朋友" },
  { t: "Write to think.", a: "—— A friend" },
  { t: "今天写 100 字，关于今天。", a: "—— Q.C." },
  { t: "笔下流出来的，是脑子没整理的。", a: "—— 给你" },
  { t: "Writing is thinking on paper.", a: "—— A friend" },
  { t: "好文笔，是改出来的。", a: "—— 朋友" },
  { t: "你想清楚了，才写得出来。", a: "—— Q.C." },
  { t: "First drafts are supposed to be ugly.", a: "—— A friend" },
  { t: "今天给未来的自己写一封信。", a: "—— 给你" },
  { t: "Daily writing > occasional masterpieces.", a: "—— A friend" },

  // === 自然 · Nature ===
  { t: "今天出去晒 15 分钟太阳。", a: "—— 朋友" },
  { t: "Touch grass. 字面意义上的。", a: "—— A friend" },
  { t: "走进自然，焦虑会自动退潮。", a: "—— Q.C." },
  { t: "看一次日落，比刷一小时手机有用。", a: "—— 给你" },
  { t: "Nature heals what humans hurt.", a: "—— A friend" },
  { t: "看树。它们不慌。", a: "—— 朋友" },
  { t: "今天注意一朵云的形状。", a: "—— Q.C." },
  { t: "Trees grow slow. So can you.", a: "—— A friend" },
  { t: "鸟叫，是宇宙的提醒：你还活着。", a: "—— 给你" },
  { t: "走出门去，世界比屏幕大。", a: "—— 朋友" },

  // === 目标 · Goals ===
  { t: "把大目标，拆成小到可笑的步骤。", a: "—— 朋友" },
  { t: "Goals are dreams with deadlines.", a: "—— A friend" },
  { t: "今天，离目标近一公分也算。", a: "—— Q.C." },
  { t: "Don't set goals. Set systems.", a: "—— A friend" },
  { t: "重要的不是目标，是养成的路径。", a: "—— 给你" },
  { t: "目标定得高，但脚步要稳。", a: "—— 朋友" },
  { t: "Aim high, walk small.", a: "—— A friend" },
  { t: "今天问自己：这件事，离我的目标近吗？", a: "—— 给你" },
  { t: "目标，是给未来的自己写的承诺。", a: "—— Q.C." },
  { t: "Vague goals = vague results.", a: "—— A friend" },

  // === 直觉 · Intuition ===
  { t: "相信你的直觉。它是经验的总和。", a: "—— 朋友" },
  { t: "Your gut knows. Listen.", a: "—— A friend" },
  { t: "脑子说不通的时候，问问心。", a: "—— Q.C." },
  { t: "犹豫不决，常常是答案已经在那。", a: "—— 给你" },
  { t: "Intuition is intelligence in a hurry.", a: "—— A friend" },
  { t: "你第一个反应，往往是对的。", a: "—— 朋友" },
  { t: "Quiet your mind to hear your heart.", a: "—— A friend" },
  { t: "如果一件事让你不安，那是身体在说话。", a: "—— Q.C." },
  { t: "Trust the whisper.", a: "—— A friend" },
  { t: "你比你以为的更懂自己。", a: "—— 朋友" },

  // === 等待 · Waiting ===
  { t: "有些事，需要时间。等等看。", a: "—— 朋友" },
  { t: "Wait without losing hope.", a: "—— A friend" },
  { t: "种子在土里的日子，看上去什么都没发生。", a: "—— Q.C." },
  { t: "Patience is also growing.", a: "—— A friend" },
  { t: "没结果的努力，正在累积。", a: "—— 给你" },
  { t: "你以为停滞，其实在酝酿。", a: "—— 朋友" },
  { t: "Good things take time.", a: "—— A friend" },
  { t: "急火攻心，是浪费火气。", a: "—— Q.C." },
  { t: "There's a season for everything.", a: "—— A friend" },
  { t: "等待，也是一种工作。", a: "—— 给你" },

  // === 友谊 · Friendship ===
  { t: "今天主动联系一个朋友。", a: "—— 朋友" },
  { t: "Friendship needs watering.", a: "—— A friend" },
  { t: "好朋友不需要每天见，但要时常想起。", a: "—— Q.C." },
  { t: "A true friend sees you. 真朋友看得见你。", a: "—— A friend" },
  { t: "今天给一个老朋友发条消息。", a: "—— 给你" },
  { t: "朋友是选的家人。", a: "—— 朋友" },
  { t: "你怎么对朋友，就是你怎么对自己。", a: "—— Q.C." },
  { t: "Show up for them. They show up for you.", a: "—— A friend" },
  { t: "听一个朋友说话，比说一小时都重要。", a: "—— 给你" },
  { t: "感谢生命中那个总是陪你的人。", a: "—— 朋友" },

  // === 困难 · Hard times ===
  { t: "现在难，是因为重要。", a: "—— 朋友" },
  { t: "Hard now, easier later.", a: "—— A friend" },
  { t: "穿过去，就成长了。", a: "—— Q.C." },
  { t: "When it's hard, you're growing.", a: "—— A friend" },
  { t: "你不是被困住，是在重新整理。", a: "—— 给你" },
  { t: "难关，是你认识自己的机会。", a: "—— 朋友" },
  { t: "What doesn't kill you, doesn't have to make you stronger — sometimes it just teaches you.", a: "—— A friend" },
  { t: "撑过来的你，会感谢现在。", a: "—— Q.C." },
  { t: "再差的日子，也是日子。", a: "—— 朋友" },
  { t: "黎明前的黑暗，最浓。", a: "—— 给你" },

  // === 接受 · Acceptance ===
  { t: "接受现在的你，才能成为想成为的你。", a: "—— 朋友" },
  { t: "Accept first. Change next.", a: "—— A friend" },
  { t: "不能改变的事，停止较劲。", a: "—— Q.C." },
  { t: "What is, is.", a: "—— A friend" },
  { t: "你的过去，造就了你。但不定义你。", a: "—— 给你" },
  { t: "和解，比对抗轻松。", a: "—— 朋友" },
  { t: "Surrender is not giving up. 是放下。", a: "—— A friend" },
  { t: "接受不等于认同，只是不抗拒。", a: "—— Q.C." },
  { t: "今天对一件你讨厌的事，说「就这样吧」。", a: "—— 给你" },
  { t: "顺其自然，才能御风而行。", a: "—— 朋友" },

  // === 信任 · Trust ===
  { t: "相信自己。哪怕没人相信。", a: "—— 朋友" },
  { t: "Trust the process. 相信流程。", a: "—— A friend" },
  { t: "你的努力，不会被辜负。", a: "—— Q.C." },
  { t: "Trust yourself first.", a: "—— A friend" },
  { t: "你做的选择，自有它的道理。", a: "—— 给你" },
  { t: "Things will work out. They usually do.", a: "—— A friend" },
  { t: "相信，是一种行动。", a: "—— 朋友" },
  { t: "对未知，保持温柔的相信。", a: "—— Q.C." },
  { t: "Believe in your story.", a: "—— A friend" },
  { t: "你已经走到这里，就是最好的证据。", a: "—— 给你" },

  // === 工作 · Work ===
  { t: "好好工作，是对自己最大的尊重。", a: "—— 朋友" },
  { t: "Do work that matters to you.", a: "—— A friend" },
  { t: "认真做事的人，运气都不会太差。", a: "—— Q.C." },
  { t: "Work hard. Rest harder.", a: "—— A friend" },
  { t: "今天把一件小事做到 110%。", a: "—— 给你" },
  { t: "认真，是一种态度。", a: "—— 朋友" },
  { t: "Care about the craft.", a: "—— A friend" },
  { t: "工作不是全部，但要全力。", a: "—— Q.C." },
  { t: "Excellence is a daily choice.", a: "—— A friend" },
  { t: "把今天交给你的事，做漂亮。", a: "—— 给你" },

  // === 钱 · Money ===
  { t: "钱是工具，不是目标。", a: "—— 朋友" },
  { t: "Money buys options, not happiness.", a: "—— A friend" },
  { t: "今天记一笔账。", a: "—— Q.C." },
  { t: "存下来的，才是你的。", a: "—— 给你" },
  { t: "Spend on experiences, save on stuff.", a: "—— A friend" },
  { t: "理财，是给未来自己留余地。", a: "—— 朋友" },
  { t: "Pay yourself first.", a: "—— A friend" },
  { t: "便宜的不一定省，贵的不一定值。", a: "—— Q.C." },
  { t: "钱花在让你成为更好的人的事情上。", a: "—— 给你" },
  { t: "Wealth = freedom to choose.", a: "—— A friend" },

  // === 一日 · The day ===
  { t: "今天，是你余生中最年轻的一天。", a: "—— 朋友" },
  { t: "Today is the day.", a: "—— A friend" },
  { t: "把今天，过成你想要的样子。", a: "—— Q.C." },
  { t: "今天 = 7×24 个生命中的一小段。珍惜。", a: "—— 给你" },
  { t: "Live this day as if it were rare.", a: "—— A friend" },
  { t: "认真地过今天。", a: "—— 朋友" },
  { t: "Today's choices = tomorrow's reality.", a: "—— A friend" },
  { t: "今天好好生活，明天才有故事讲。", a: "—— Q.C." },
  { t: "Make today count.", a: "—— A friend" },
  { t: "今天的每一刻，都是唯一的。", a: "—— 给你" },

  // === 旅程 · Journey ===
  { t: "你不是要去某个地方，你是在过程里。", a: "—— 朋友" },
  { t: "The journey is the destination.", a: "—— A friend" },
  { t: "享受这条路，别只盯着终点。", a: "—— Q.C." },
  { t: "Enjoy the climb.", a: "—— A friend" },
  { t: "终点不是为了到达，是为了出发。", a: "—— 给你" },
  { t: "Wherever you are, you're on the way.", a: "—— A friend" },
  { t: "每一步，都算数。", a: "—— 朋友" },
  { t: "Pause and look around.", a: "—— A friend" },
  { t: "停下来看看你已经走了多远。", a: "—— Q.C." },
  { t: "你走的每一步，都是路。", a: "—— 给你" },

  // === 学校 / 考试 · School / Exams ===
  { t: "考前焦虑很正常。它说明你在乎。", a: "—— 朋友" },
  { t: "You're more prepared than you think.", a: "—— A friend" },
  { t: "复习一遍，胜过看 5 遍新内容。", a: "—— Q.C." },
  { t: "考试，不定义你。", a: "—— 给你" },
  { t: "A test is just a snapshot, not your story.", a: "—— A friend" },
  { t: "尽力就好。结果交给时间。", a: "—— 朋友" },
  { t: "今天主动回忆，比被动看书有用 10 倍。", a: "—— Q.C." },
  { t: "Sleep before an exam > cram all night.", a: "—— A friend" },
  { t: "你已经走到这里，已经赢了。", a: "—— 给你" },
  { t: "考试是一次机会，不是审判。", a: "—— 朋友" },

  // === 英语 · Language ===
  { t: "每天 20 分钟，胜过周末 5 小时。", a: "—— 朋友" },
  { t: "Speak before you're ready.", a: "—— A friend" },
  { t: "怕说错？错了才学得快。", a: "—— Q.C." },
  { t: "Immersion > memorization.", a: "—— A friend" },
  { t: "今天读一篇你喜欢的文章。", a: "—— 给你" },
  { t: "学一门语言，就是多一种看世界的方式。", a: "—— 朋友" },
  { t: "Mistakes are language acquisition.", a: "—— A friend" },
  { t: "今天试着用英文记笔记。", a: "—— Q.C." },
  { t: "Listen first. Speak when ready.", a: "—— A friend" },
  { t: "今天背 5 个单词，就好。", a: "—— 给你" },

  // === 编程 · Coding ===
  { t: "Bug 不是敌人，是老师。", a: "—— 朋友" },
  { t: "Read the error message. 真的，再读一遍。", a: "—— A friend" },
  { t: "今天写一个能跑的 bug。", a: "—— Q.C." },
  { t: "Write code for humans first, computers second.", a: "—— A friend" },
  { t: "看一千行教程，不如自己写 100 行。", a: "—— 给你" },
  { t: "代码写完了，再写注释。", a: "—— 朋友" },
  { t: "Refactor mercilessly.", a: "—— A friend" },
  { t: "Stuck? 解决一半，剩下一半睡醒再说。", a: "—— Q.C." },
  { t: "Best code is no code.", a: "—— A friend" },
  { t: "今天提交一次。哪怕只改了一行。", a: "—— 给你" },

  // === 创意 · Creativity ===
  { t: "创意不是天才的礼物，是练出来的。", a: "—— 朋友" },
  { t: "Creativity is showing up.", a: "—— A friend" },
  { t: "今天画一张丑画。", a: "—— Q.C." },
  { t: "Don't wait for inspiration. Work for it.", a: "—— A friend" },
  { t: "做一件不为生产力的事。", a: "—— 给你" },
  { t: "灵感，给已经动手的人。", a: "—— 朋友" },
  { t: "Steal like an artist. 但要消化。", a: "—— A friend" },
  { t: "无聊，是创意的母亲。", a: "—— Q.C." },
  { t: "Boredom births brilliance.", a: "—— A friend" },
  { t: "今天，主动让自己无聊 10 分钟。", a: "—— 给你" },

  // === 反卷 · Anti-grind ===
  { t: "卷不是努力。卷是焦虑。", a: "—— 朋友" },
  { t: "Hustle culture is a trap.", a: "—— A friend" },
  { t: "今天少做一件事，多走一段路。", a: "—— Q.C." },
  { t: "Productivity ≠ life.", a: "—— A friend" },
  { t: "你不必每分钟都有用。", a: "—— 给你" },
  { t: "工作填满人生，是骗局。", a: "—— 朋友" },
  { t: "Slow living is also living.", a: "—— A friend" },
  { t: "你不是机器。今晚关电脑。", a: "—— Q.C." },
  { t: "Rest is rebellion.", a: "—— A friend" },
  { t: "活着不是为了产出。", a: "—— 给你" },

  // === 整理 · Tidy ===
  { t: "桌面整洁，脑子才整洁。", a: "—— 朋友" },
  { t: "Tidy space, tidy mind.", a: "—— A friend" },
  { t: "今天扔掉 3 件不需要的东西。", a: "—— Q.C." },
  { t: "Clutter is decisions waiting.", a: "—— A friend" },
  { t: "整理，是和过去和解。", a: "—— 给你" },
  { t: "扫一次地，是一次冥想。", a: "—— 朋友" },
  { t: "Touch each item. Keep what sparks joy.", a: "—— A friend" },
  { t: "今天整理一个抽屉，不要多。", a: "—— Q.C." },
  { t: "外在的混乱，是内在的镜子。", a: "—— 给你" },
  { t: "Less stuff, more space — for everything.", a: "—— A friend" },

  // === 仪式感 · Rituals ===
  { t: "给生活一些小仪式。", a: "—— 朋友" },
  { t: "Rituals turn the ordinary into sacred.", a: "—— A friend" },
  { t: "今晚点根蜡烛吃饭。", a: "—— Q.C." },
  { t: "Make your coffee slowly.", a: "—— A friend" },
  { t: "周末做一次像样的早餐。", a: "—— 给你" },
  { t: "认真泡一杯茶，也是修行。", a: "—— 朋友" },
  { t: "Small rituals, big peace.", a: "—— A friend" },
  { t: "给一周的开始和结束，加点仪式。", a: "—— Q.C." },
  { t: "Daily rituals = daily anchors.", a: "—— A friend" },
  { t: "在重要的事情前，停 5 秒。", a: "—— 给你" },

  // === 慈悲 · Compassion ===
  { t: "对别人慈悲，对自己也是。", a: "—— 朋友" },
  { t: "Everyone is fighting their own battle.", a: "—— A friend" },
  { t: "今天对一个陌生人微笑。", a: "—— Q.C." },
  { t: "Kindness is free. 慷慨一点。", a: "—— A friend" },
  { t: "你说出口的话，会留在别人心里。", a: "—— 给你" },
  { t: "今天的善意，未来会回来。", a: "—— 朋友" },
  { t: "Compassion costs nothing.", a: "—— A friend" },
  { t: "听别人说话时，不打断。", a: "—— Q.C." },
  { t: "In a world of cold, be warm.", a: "—— A friend" },
  { t: "做一个让别人放松的人。", a: "—— 给你" },

  // === 反内耗 · Stop overthinking ===
  { t: "想多了，做少了。今天就动起来。", a: "—— 朋友" },
  { t: "Overthinking is fear in disguise.", a: "—— A friend" },
  { t: "你不是在思考，你是在反复焦虑。", a: "—— Q.C." },
  { t: "停止内耗的方法，是开始行动。", a: "—— 给你" },
  { t: "Get out of your head.", a: "—— A friend" },
  { t: "想清楚没那么重要。先做。", a: "—— 朋友" },
  { t: "Action beats analysis.", a: "—— A friend" },
  { t: "Just do the next small thing.", a: "—— A friend" },
  { t: "把脑子里的念头写下来，它就消停了。", a: "—— Q.C." },
  { t: "你不必赢得脑子里的每场辩论。", a: "—— 给你" },

  // === 友善 · Be soft ===
  { t: "在一个变硬的世界里，请保持柔软。", a: "—— 朋友" },
  { t: "Softness is also a strength.", a: "—— A friend" },
  { t: "温柔的人，最有力量。", a: "—— Q.C." },
  { t: "Don't let the world harden you.", a: "—— A friend" },
  { t: "你的善良，没有人配得上嘲笑。", a: "—— 给你" },
  { t: "温柔，是一种选择，不是天性。", a: "—— 朋友" },
  { t: "Be gentle with everyone, including yourself.", a: "—— A friend" },
  { t: "今天放过一个人，包括你自己。", a: "—— Q.C." },
  { t: "Kindness is not weakness.", a: "—— A friend" },
  { t: "做一个柔软但坚定的人。", a: "—— 给你" },

  // === 终曲 · Closing ===
  { t: "你已经做得很好了。", a: "—— 朋友" },
  { t: "You're doing better than you think.", a: "—— A friend" },
  { t: "今天的你，已经够好。", a: "—— Q.C." },
  { t: "Be proud of how far you've come.", a: "—— A friend" },
  { t: "未来不会辜负今天努力的你。", a: "—— 给你" },
  { t: "Keep going. The world needs you.", a: "—— A friend" },
  { t: "你存在，本身就是好事。", a: "—— 朋友" },
  { t: "You are loved. 真的。", a: "—— A friend" },
  { t: "再见。明天见。", a: "—— Q.C." },
  { t: "今天，请为自己骄傲一下。", a: "—— 给你" },
];

window.REFLECTION_PROMPTS = [
  "今天有什么让你觉得「我做得不错」的小瞬间？",
  "What surprised you today? 今天有什么出乎意料的事？",
  "如果重新过一遍今天，你会做哪一件事不一样？",
  "今天你对自己温柔了吗？",
  "What's one thing you learned today — 哪怕是关于自己？",
  "今天有谁/什么帮助了你？记下来。",
  "今天最让你专注的事是什么？为什么？",
  "今天的你，是你想成为的那种人吗？哪些部分是？",
  "明天，你想多做一点什么？少做一点什么？",
  "What energized you today? What drained you?",
  "今天的你，比上周一的你，多懂了什么？",
  "如果今天有一句话送给未来的自己，是什么？",
];
